baseurl = "https://marcopollivier.dev/"
title = "Marco Paulo Ollivier"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "marcopollivier"

[params]
    author = "Marco Paulo Ollivier"
    info = "Software Engineer @ Nubank"
    description = "Página pessoal de Marco Paulo Ollivier"
    keywords = "blog,developer,personal,software engineer "
    footercontent = "Fale comigo pelo e-mail <a href='mailto://mollivier.dev@gmail.com'>mollivier.dev@gmail.com</a>"

    avatarurl = "https://avatars1.githubusercontent.com/u/697445?s=460&v=4"
    #gravatar = "john.doe@example.com"

    favicon_32 = "img/favicon-32x32.png"
    favicon_16 = "img/favicon-16x16.png"

    since = 2012

    enableTwemoji = true
    
    colorScheme = "dark"
    hidecolorschemetoggle = false

    # hidecredits = true
    # hidecopyright = true

    custom_css = ["css/custom.css"]
    custom_scss = ["scss/custom.scss"]
    custom_js = ["js/custom.js"]

[permalinks]
  posts = '/:year/:month/:title/'

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
# Social Media
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/marcopollivier"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    url = "https://twitter.com/marcopollivier/"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    url  = "https://instagram.com/marcopollivier"
# [[params.social]]
#     name = "Telegram"
#     icon = "fa fa-telegram-plane "
#     url  = "https://t.me/marcopollivier"

# Content
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium fa-2x"
    url  = "https://medium.com/@marcopollivier"
# [[params.social]]
#     name = "Dev.to"
#     icon = "fa fa-dev "
#     url = "https://dev.to/marcopollivier"
# [[params.social]]
#     name = "Speaker Deck"
#     icon = "fa fa-speaker-deck"
#     url = "https://speakerdeck.com/marcopollivier"
[[params.social]]
    name = "YouTube"
    icon = "fa fa-youtube fa-2x"
    url  = "https://youtube.com/user/marcopollivier"

# Repos
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    url = "https://github.com/marcopollivier"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab fa-2x"
    url = "https://gitlab.com/marcopollivier"
# [[params.social]]
#     name = "npm"
#     icon = "fa fa-npm"
#     url = "https://www.npmjs.com/~marcopollivier"

# Others
[[params.social]]
    name = "Stack Overflow"
    icon = "fa fa-stack-overflow fa-2x"
    url  = "https://stackoverflow.com/users/1913089/marco-paulo-ollivier"
[[params.social]]
    name = "Meetup"
    icon = "fa fa-meetup fa-2x"
    url  = "https://www.meetup.com/members/233822612"
[[params.social]]
    name = "Pocket"
    icon = "fa fa-get-pocket fa-2x"
    url  = "https://getpocket.com/@marcopollivier"

# Menu links
#[[menu.main]]
#    name = "GopheRio Meetup"
#    url = "https://gopher.rio.br"
#[[menu.main]]
#    name = "Cursos"
#    url = "#"
# [[menu.main]]
#     name = "Tech"
#     url = "http://responsive.com.br"
# [[menu.main]]
#     name = "Ciências"
#     # url = "https://relativity.com.br"
#     url = "https://medium.com/relatividade-cotidiana"
# [[menu.main]]
#     name = "Filosofia"
#     url = "https://medium.com/philossophiapura"
# [[menu.main]]
#     name = "Foodie"
#     url = "https://medium.com/bacalhaufoodie"
#[[menu.main]]
#    name = "Fotografia"
#    url = "#"
