baseurl = "https://marcopollivier.dev/"
title = "Marco Ollivier"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"
paginate = 20
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true
disqusShortname = "marcopollivier"

[params]
author = "Marco Ollivier"
description = "Página pessoal de Marco Ollivier"
keywords = "blog,developer,personal,software engineer "
info = "Software Engineer @ Flash"
gravatar = "marcopollivier@gmail.com"
dateFormat = "January 2, 2006"
since = 2012
colorScheme = "auto"
hidecolorschemetoggle = false
maxSeeAlsoItems = 5
custom_css = ["css/custom.css"]
custom_scss = ["scss/custom.scss"]
custom_js = ["js/custom.js"]

[params.googleTagManager]
id = "GTM-WKCPJV9"

[taxonomies]
  category = "categorias"
  series = "series"
  tag = "tags"
  author = "autores"

# Social links
# Social Media
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/marcopollivier"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    url = "https://twitter.com/marcopollivier/"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    url  = "https://instagram.com/marcopollivier"
# [[params.social]]
#     name = "Telegram"
#     icon = "fa fa-telegram-plane "
#     url  = "https://t.me/marcopollivier"

# Content
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium fa-2x"
    url  = "http://responsive.com.br"
# [[params.social]]
#     name = "Dev.to"
#     icon = "fa fa-dev "
#     url = "https://dev.to/marcopollivier"
# [[params.social]]
#     name = "Speaker Deck"
#     icon = "fa fa-speaker-deck"
#     url = "https://speakerdeck.com/marcopollivier"
[[params.social]]
    name = "YouTube"
    icon = "fa fa-youtube fa-2x"
    url  = "https://youtube.com/user/marcopollivier"

# Repos
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    url = "https://github.com/marcopollivier"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab fa-2x"
    url = "https://gitlab.com/marcopollivier"
# [[params.social]]
#     name = "npm"
#     icon = "fa fa-npm"
#     url = "https://www.npmjs.com/~marcopollivier"

# Others
[[params.social]]
    name = "Stack Overflow"
    icon = "fa fa-stack-overflow fa-2x"
    url  = "https://stackoverflow.com/users/1913089/marco-paulo-ollivier"
[[params.social]]
    name = "Meetup"
    icon = "fa fa-meetup fa-2x"
    url  = "https://www.meetup.com/members/233822612"
[[params.social]]
    name = "Pocket"
    icon = "fa fa-get-pocket fa-2x"
    url  = "https://getpocket.com/@marcopollivier"

[languages.pt-br]
languageName = ":brazil:"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

#[[languages.pt-br.menu.main]]
#name = "Blog"
#weight = 2
#url = "posts/"
#
#[[languages.pt-br.menu.main]]
#name = "Cursos"
#weight = 3
#url = "classes/"
#
#[[languages.pt-br.menu.main]]
#name = "Projetos"
#weight = 4
#url = "projects/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

#[[languages.en.menu.main]]
#name = "Blog"
#weight = 2
#url = "posts/"
#
#[[languages.en.menu.main]]
#name = "Classes"
#weight = 3
#url = "classes/"
#
#[[languages.en.menu.main]]
#name = "Projects"
#weight = 4
#url = "projects/"
