baseurl = "https://ollivier.com.br"
title = "Marco Paulo Ollivier"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Marco Paulo Ollivier"
    info = "Software Engineer @ Nubank"
    description = "Marco Paulo Ollivier's personal website"
    keywords = "blog,developer,personal"
    footercontent = "Descendente intelectual de Arquimedes"

    avatarurl = "https://avatars1.githubusercontent.com/u/697445?s=460&v=4"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium-m"
    url  = "https://medium.com/@marcopollivier"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    url = "https://twitter.com/marcopollivier/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/marcopollivier"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    url = "https://github.com/marcopollivier/"
[[params.social]]
    name = "Meetup"
    icon = "fab fa-meetup"
    url  = "https://www.meetup.com/members/233822612"
[[params.social]]
    name = "Pocket"
    icon = "fab fa-get-pocket"
    url  = "https://getpocket.com/@marcopollivier"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    url  = "https://stackoverflow.com/users/1913089/marco-paulo-ollivier"

# Menu links
[[menu.main]]
    name = "Palestras"
    url = "https://speakerdeck.com/marcopollivier"
[[menu.main]]
    name = "Blog de Soft. Eng."
    url = "http://responsive.com.br"
[[menu.main]]
    name = "GopheRio Meetup"
    url = "https://gopher.rio.br"
[[menu.main]]
    name = "Blog de Ciência"
    url = "https://relativity.com.br"
