baseurl = "https://ollivier.com.br"
title = "Marco Paulo Ollivier"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Marco Paulo Ollivier"
    info = "Software Engineer @ OLX"
    description = "Marco Paulo Ollivier's personal website"
    keywords = "blog,developer,personal"
    footercontent = "Descendente intelectual de Arquimedes"

    avatarurl = "https://avatars1.githubusercontent.com/u/697445?s=460&v=4"
    
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
   
    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Responsive - My Tech Blog"
    icon = "fab fa-medium-m"
    url  = "http://responsive.com.br"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    url = "https://twitter.com/marcopollivier/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/marcopollivier"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    url = "https://github.com/marcopollivier/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    url = "https://gitlab.com/marcopollivier/"
[[params.social]]
    name = "Bitbucket"
    icon = "fab fa-bitbucket fa-2x"
    url = "https://bitbucket.org/marcopollivier/"
[[params.social]]
    name = "Meetup"
    icon = "fab fa-meetup"
    url  = "https://www.meetup.com/members/233822612"
[[params.social]]
    name = "Pocket"
    icon = "fab fa-get-pocket"
    url  = "https://getpocket.com/@marcopollivier"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    url  = "https://stackoverflow.com/users/1913089/marco-paulo-ollivier"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     url = "https://medium.com/@marcopollivier"
[[menu.main]]
    name = "Presentation"
    url = "https://speakerdeck.com/marcopollivier"
[[menu.main]]
    name = "Meetup (soon)"
    url = "#"
[[menu.main]]
    name = "My Science Blog"
    url = "https://relativity.com.br"