baseurl = "https://ollivier.com.br"
title = "Marco Paulo Ollivier"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "marcopollivier"

[params]
    author = "Marco Paulo Ollivier"
    info = "Software Engineer @ Nubank"
    description = "Página pessoal de Marco Paulo Ollivier"
    keywords = "blog,developer,personal"
    footercontent = "Fale comigo pelo e-mail <a href='mailto://mollivier.dev@gmail.com'>mollivier.dev@gmail.com</a>"

    avatarurl = "https://avatars1.githubusercontent.com/u/697445?s=460&v=4"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/marcopollivier"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    url = "https://twitter.com/marcopollivier/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    url  = "https://instagram.com/marcopollivier"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram-plane"
    url  = "https://t.me/marcopollivier"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium-m"
    url  = "https://medium.com/@marcopollivier"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    url = "https://github.com/marcopollivier"
[[params.social]]
    name = "npm"
    icon = "fab fa-npm"
    url = "https://www.npmjs.com/~marcopollivier"
[[params.social]]
    name = "Speaker Deck"
    icon = "fab fa-speaker-deck"
    url = "https://speakerdeck.com/marcopollivier"
[[params.social]]
    name = "Dev.to"
    icon = "fab fa-dev"
    url = "https://dev.to/marcopollivier"
[[params.social]]
    name = "Meetup"
    icon = "fab fa-meetup"
    url  = "https://www.meetup.com/members/233822612"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    url  = "https://stackoverflow.com/users/1913089/marco-paulo-ollivier"
[[params.social]]
    name = "Pocket"
    icon = "fab fa-get-pocket"
    url  = "https://getpocket.com/@marcopollivier"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube"
    url  = "https://youtube.com/user/marcopollivier"

# Menu links
[[menu.main]]
    name = "Blog Tech"
    url = "http://responsive.com.br"
[[menu.main]]
    name = "GopheRio Meetup"
    url = "https://gopher.rio.br"
[[menu.main]]
    name = "Blog de Ciência"
    url = "https://relativity.com.br"
